services:

  backend:
    build: .
    container_name: educational-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    container_name: educational-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: educational-postgres
    environment:
      POSTGRES_DB: api_courses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d